---
# file : _uninstall.yml
# description : uninstall gh runner package


- name: GitHub Actions Runner [!!] DESTROY! | Uninstall service
  become: true
  ansible.builtin.command:
    cmd: "{{ gh_runner_path }}/svc.sh uninstall"
    chdir: "{{ gh_runner_path }}"
  when: "{{ ansible_os_family != 'Darwin' }}"

- name: GitHub Actions Runner [!!] DESTROY! | De-register Runner
  become: true
  ansible.builtin.command:
    cmd: |-
      {{ gh_runner_path }}/config.sh remove \
        --token "{{ gh_runner_config_token }}"
    chdir: "{{ gh_runner_path }}"

- name: GitHub Actions Runner [!!] DESTROY! | Delete workspace and installations
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ gh_runner_installation_path }}/"
    - "{{ gh_runner_workspace_path }}/"

