---
galaxy_info:
  role_name: github_actions_runner
  author: Matheus Cunha
  description: >
    Idempotent Ansible role that installs and configures self-hosted GitHub
    Actions Runners (yeah, plural!)
  license: MIT
  company: None
  min_ansible_version: "2.2"
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - github
    - actions
    - workflows
    - runner
